apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # name of the currently deploying app in argocd, this is the name that will be displayed in ArgoCD
  name: "common-deployer" # name of the deploying app in argocd
  namespace: argocd # namespace of your argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/ForumViriumHelsinki/TFDS_SIMPL-open_common_components.git"
    path: charts
    targetRevision: main # version of package
    helm:
      values: |
        values:
          repo_URL: 'https://github.com/ForumViriumHelsinki/TFDS_SIMPL-open_common_components.git'
          branch: main                           # branch of repo with values
        resourcePreset: low                     # set to "low" to disable requests of resources
        agentList:                                  # list of all the agents to be deployed, note that for single node, only use one agent.
          authorities:
            - authority
          consumers:
            - consumer
          providers:
            - dataprovider
        project: default                            # Project to which the namespace is attached
        namespaceTag: common                      # identifier of deployment and part of fqdn
        domainSuffix: ds.helsinki.tfds.io           # last part of fqdn
        argocd:
          appname: common                         # name of generated argocd app
          namespace: argocd                         # namespace of your argocd
        cluster:
          # FQDN Fully Qualified Domain Name of your kubernetes cluster
          address: https://kubernetes.default.svc
          namespace: common                       # where the app will be deployed
          issuer: dev-prod                          # issuer of certificate
          internalIssuer: self-signed-issuer            # issuer of self-signed certificates
          kubeStateHost: kube-prometheus-stack-kube-state-metrics.devsecopstools.svc.cluster.local:8080    # link to kube-state-metrics svc
        secrets:
          secretEngine: example                     # name of the kv secret engine that will be created in OpenBao
          role: example-role                        # name of the role that will be created in OpenBao
        pg_cluster:
          ha: false                                 # set to false to have one replica of Postgres to save resources
        openbao:
          ha: false                                 # set to false to have one replica of OpenBao to save resources
        kafka:
          ha: false                                 # true creates 3 replicas of each component, false creates 1 of each
          topic:
            autocreate: true
        infrastructure_consumption_monitoring_service:
          enabled: false                            # Set to false to disable OVH-specific billing scraper
        mailpit:
          # set this value to true, to have mailpit activated (sandbox mode)
          enabled: false
        smtp:
          host: "email-smtp.tfds.io"
          user: "smtp"
          defaultReceiver: "admin@ds.helsinki.tfds.io"
        monitoring:          # set this value to true, to enable the monitoring features
          enabled: false
  destination:
    # FQDN Fully Qualified Domain Name of your kubernetes cluster
    server: "https://kubernetes.default.svc"
    # Name of the Kubernetes NameSpace in which the Common Tools will be deployed
    namespace: common
